"""Trip domain services."""
import logging
from datetime import date, timedelta

from apps.ai.schemas import ItineraryDraft
from apps.trips.documents import Activity, Itinerary, ItineraryDay, Trip

logger = logging.getLogger(__name__)

DEFAULT_START_OFFSET_DAYS = 30


def _resolve_dates(requirements: dict, days_count: int) -> tuple[date, date]:
    start = requirements.get("start_date")
    if isinstance(start, str):
        try:
            start = date.fromisoformat(start[:10])
        except ValueError:
            start = None
    if start is None:
        start = date.today() + timedelta(days=DEFAULT_START_OFFSET_DAYS)
    end = start + timedelta(days=max(1, days_count) - 1)
    return start, end


def create_trip_from_itinerary(
    *,
    owner_public_id: str,
    requirements: dict,
    draft: ItineraryDraft,
    engine: str,
) -> Trip:
    """Persist a validated AI/demo itinerary as a Trip owned by ``owner``."""
    days = draft.days
    start, end = _resolve_dates(requirements, len(days))

    itinerary = Itinerary(
        days=[
            ItineraryDay(
                day_number=index,
                date=start + timedelta(days=index - 1),
                title=day.title or f"Day {index}",
                activities=[
                    Activity(
                        name=a.name,
                        description=a.description,
                        start_time=a.start_time,
                        duration_minutes=a.duration_minutes,
                        location_name=a.location_name or draft.destination,
                        latitude=a.latitude,
                        longitude=a.longitude,
                        category=a.category,
                        cost_estimate=float(a.cost_estimate),
                    )
                    for a in day.activities
                ],
            )
            for index, day in enumerate(days, start=1)
        ]
    )

    from apps.trips.exchange import convert

    travelers = int(requirements.get("travelers") or 2)
    base_currency = "PKR"
    # AI cost estimates arrive as per-person USD figures; the demo engine
    # already prices per group. Normalise everything into the PKR base display
    # currency so every figure a user sees is consistent and convertible.
    cost_scale = travelers if engine == "openai" else 1
    for day in itinerary.days:
        for activity in day.activities:
            per_person = float(activity.cost_estimate or 0)
            activity.cost_estimate = round(
                convert(per_person, "USD", base_currency) * cost_scale, 2
            )

    stated_currency = str(requirements.get("budget_currency") or base_currency)
    budget_amount = (
        convert(float(requirements["budget_amount"]), stated_currency, base_currency)
        if requirements.get("budget_amount")
        else None
    )
    # Keep the scoring pipeline on the same (PKR) basis as the stored figures.
    if requirements.get("budget_amount") is not None:
        requirements["budget_amount"] = budget_amount
    requirements["budget_currency"] = base_currency

    duration = max(1, min(len(days), 365))
    style = str(requirements.get("travel_style") or "balanced")
    title = f"{duration}-day {style} trip to {draft.destination}"

    trip = Trip(
        owner_public_id=owner_public_id,
        title=title[:200],
        destination=draft.destination,
        start_date=start,
        end_date=end,
        duration_days=duration,
        travelers=travelers,
        budget_amount=budget_amount,
        budget_currency=base_currency,
        budget_level=str(requirements.get("budget_level") or "moderate"),
        travel_style=style,
        interests=list(requirements.get("interests") or []),
        status="planned",
        visibility="private",
        notes=f"Generated by WanderSync ({engine} engine).",
        itinerary=itinerary,
    )
    # Optimize routing/schedule, then score transparently (Phase 7).
    from apps.itineraries.optimizer import optimize_trip

    score = optimize_trip(trip, requirements)
    trip.save()
    logger.info(
        "Trip %s created from %s itinerary (%d days, score %s)",
        trip.id,
        engine,
        duration,
        score["score"],
    )
    return trip

